#!/bin/bash

for file in $@
do
	if [ -d $file ]
	then 
		echo $file is a directory, skipping
	else
		echo Processing $file
		if [ "${1##*.}" != "java" ]
		then
			echo Warning: $file does not appear to be a Java source file
		fi
		cat > /tmp/licence.$file.$$ << END_OF_LICENCE
/*
 * JGAAP -- Java Graphical Authorship Attribution Program
 * Copyright (C) 2009 by Patrick Juola
 * 
 * This program is free software: you can redistribute it and/or modify
 * under the terms of the GNU General Public License as published by
 * the Free Software Foundation, version 3.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * For questions, contact Patrick Juola at Duquesne University, Pittsburgh,
 * PA, or via email at juola@mathcs.duq.edu
 */

END_OF_LICENCE
		cat $file >> /tmp/licence.$file.$$
		if [ -x $file ]
		then
			chmod a+x /tmp/licence.$file.$$
		fi
		rm $file
		cp /tmp/licence.$file.$$ $file
		echo Processed $file
	fi
#	rm /tmp/licence*.$$
done
